# n = 3

In [3]:
import numpy as np
 
n = 3 #3個變數

A= np.random.randint(-10,10,size=(n,n)) #係數隨機範圍-10 ~ 10

np.random.seed(1) #給定亂數種子

b= np.random.randint(-10,10,size=(n,1)) #給定每個方程式的值 範圍-10 ~ 10

x= np.linalg.solve(A, b) #解聯立方程


print( 

f''' 

n= {n},  

A= {A} 

b= {b} 

x= {x} 

''') 

 

n= 3,  

A= [[ 8 -5  8]
 [ 1  0  4]
 [ 8 -6 -1]] 

b= [[-5]
 [ 1]
 [ 2]] 

x= [[10.14285714]
 [13.57142857]
 [-2.28571429]] 




# n = 5

In [4]:
n = 5 #5個變數

A= np.random.randint(-10,10,size=(n,n)) #係數隨機範圍-10 ~ 10

np.random.seed(1) #給定亂數種子

b= np.random.randint(-10,10,size=(n,1)) #給定每個方程式的值 範圍-10 ~ 10

x= np.linalg.solve(A, b) #解聯立方程


print( 

f''' 

n= {n},  

A= {A} 

b= {b} 

x= {x} 

''') 

 

n= 5,  

A= [[ -2  -1   1  -5   5]
 [-10   6  -9   2  -3]
 [  3  -4   8  -5   8]
 [  1   0   4   8  -6]
 [ -1   7 -10   3  -1]] 

b= [[-5]
 [ 1]
 [ 2]
 [-2]
 [-1]] 

x= [[ -13.64874552]
 [-100.04301075]
 [ -53.7562724 ]
 [  66.18637993]
 [  50.46953405]] 




# n = 10

In [5]:
n = 10 #10個變數

A= np.random.randint(-10,10,size=(n,n)) #係數隨機範圍-10 ~ 10

np.random.seed(1) #給定亂數種子

b= np.random.randint(-10,10,size=(n,1)) #給定每個方程式的值 範圍-10 ~ 10

x= np.linalg.solve(A, b) #解聯立方程


print( 

f''' 

n= {n},  

A= {A} 

b= {b} 

x= {x} 

''') 

 

n= 10,  

A= [[  1  -5   5 -10   6  -9   2  -3   3  -4]
 [  8  -5   8   1   0   4   8  -6  -1   7]
 [-10   3  -1  -1  -3  -9 -10   7  -2   3]
 [  9   5   0  -2  -3  -7  -4   7  -7  -6]
 [  7   1   2   6   3   9  -1   8   5 -10]
 [ -6   5  -8  -3  -2  -1  -7  -3  -6  -5]
 [  9  -4  -2 -10  -8   0   5   5  -3   9]
 [  0   4 -10  -9   7   3  -7 -10   3  -4]
 [ -4  -8   2   1  -3   3  -2   1   2   1]
 [ -6  -3  -3   3  -6   6   8 -10   3   0]] 

b= [[ -5]
 [  1]
 [  2]
 [ -2]
 [ -1]
 [  1]
 [ -5]
 [  5]
 [-10]
 [  6]] 

x= [[-0.23666858]
 [ 2.24914947]
 [ 1.14820126]
 [-0.53803661]
 [-0.87130973]
 [ 0.37778005]
 [ 0.03547092]
 [-0.56274701]
 [ 0.99345816]
 [ 0.18765873]] 


